# This workflow is used to augment the capabilities of the renovate GitHub app by running a full
# `nx migrate` when renovate opens a PR to change the version of nx in package.json.
#
# You will therefore also notice that in the renovate configuration, we ignore any packages which
# Nx will manage for us as part of `nx migrate` such as the remaining @nx/* packages.

name: Nx Migrate

on:
  # NOTE: Never use pull_request_target here because that would populate secrets for forks
  # Renovate creates branches directly on the main repo and acts like a trusted contributor
  pull_request:
    branches: [main]
    paths:
      - 'package.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

# Minimal permissions by default
permissions:
  contents: read

jobs:
  maybe_nx_migrate:
    # Only run if it was the renovate bot that triggered the workflow (otherwise we'll create a loop)
    if: contains('["renovate[bot]"]', github.actor) == true
    name: Run nx migrate if required
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # To allow us to perform the git diff we need the git history
          fetch-depth: 0
          # To ensure we can push from a different user (and therefore cause actions to rerun)
          persist-credentials: false

      - name: Check if nx was changed as part of the latest commit on the PR
        id: nx-workspace-package-check
        run: |
          git diff HEAD~1 -G"nx" --exit-code package.json && echo "nx unchanged" || echo "::set-output name=was-changed::true"

      - name: Install Node.js per package.json
        if: ${{ steps.nx-workspace-package-check.outputs.was-changed == 'true' }}
        uses: actions/setup-node@v5
        with:
          cache: 'npm'

      - name: Run nx migrate if nx changed and commit the results
        if: ${{ steps.nx-workspace-package-check.outputs.was-changed == 'true' }}
        env:
          # We cannot use secrets.GITHUB_TOKEN for this because it is not permitted to kick off subsequent actions worfklow runs, so we use a fine grained PAT instead
          GITHUB_TOKEN: ${{ secrets.GH_FINE_GRAINED_PAT }}
          # We don't want to run any of our postinstall logic when Nx is invoking install behind the scenes
          SKIP_POSTINSTALL: 'true'
        run: |
          # Checkout the PR branch using the github CLI
          gh pr checkout ${{ github.event.pull_request.number }}

          # Get the version of Nx we are migrating to
          NX_VERSION=$(node -e "console.log(require('./package.json').devDependencies['nx'])")

          # Revert renovate's changes to package.json and pnpm-lock.yaml so that it is a clean migrate from the status quo
          git checkout HEAD~1 -- package.json package-lock.json

          # We need to expect lock file changes to be applicable
          npm ci --legacy-peer-deps

          npx nx migrate $NX_VERSION

          # Sometimes Nx can require config formatting changes after a migrate command
          # We need to expect lock file changes to be applicable
          npm install --ignore-scripts --legacy-peer-deps

          # migrations.json may or may not exist after running nx migrate
          if [ -f migrations.json ]; then
            npx nx migrate --run-migrations=migrations.json

            # After we have run its migrations, we no longer need the migrations.json file
            rm migrations.json
          fi

          # Commit all the changes to the PR (see note on not being able to use secrets.GITHUB_TOKEN for this)
          git config --global user.email "cferry09@gmail.com"
          git config --global user.name "Coly010"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git

          git add .
          git commit -m "chore: run nx migrate for nx v$NX_VERSION"
          git push
